name:                adventOfCode2020
version:             0.1.0.0
github:              "ethanrcohen/adventOfCode2020"
license:             BSD3
author:              "Ethan Cohen"
maintainer:          "ecohen56@gmail.com"
copyright:           "2020 Ethan Cohen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ethanrcohen/adventOfCode2020#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers

library:
  source-dirs: src

executables:
  day1:
    main:                Main.hs
    source-dirs:         src/day1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2020

  day2:
    main:                Main.hs
    source-dirs:         src/day2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2020

  day3:
    main:                Main.hs
    source-dirs:         src/day3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2020

  day4:
    main:                Main.hs
    source-dirs:         src/day4 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2020

